# Generated by Django 4.0.6 on 2023-11-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplolibros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='libro',
            name='unidades_disponibles',
            field=models.IntegerField(default=0),
        ),
    ]
