# Generated by Django 4.0.6 on 2023-11-30 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusergroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='customusergroup',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuserpermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='customuserpermission',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='CustomUserGroup',
        ),
        migrations.DeleteModel(
            name='CustomUserPermission',
        ),
    ]
